baseURL: "https://jlkim.github.io" 
title: J. Leo Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Misc.
          url: misc/
          weight: 3

params:
    description: "Website of Leo Kim"
    author: Jungjoon Leo Kim
    # googleAnalyticsID: "G-FQDGD8LV4J"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","misc"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jungjoon Leo Kim
          subtitle: "I am a Postdoctoral Fellow at York University in Toronto, Ontario, Canada. I am a theoretical physicist, interested in dark matter phenomenology and cosmology/astrophysics. Prior to working at York, I did my PhD at with [Joe Bramante](https://www.queensu.ca/academia/bramante/) at Queen's University in Kingston, Ontario, Canada, and my Master of Mathematics working with [Ghazal Geshnizjani](https://ghazalgeshnizjani.wordpress.com/) at the University of Waterloo in Waterloo, Ontario, Canada."
          imageUrl: "icon.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Misc
              url: misc/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jlkim@yorku.ca
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: Inspire
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2


