baseURL: "https://jlkim.github.io" 
title: J. Leo Kim
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Publications
          url: https://inspirehep.net/authors/1945407
          weight: 3
        - name: Misc.
          url: misc/
          weight: 4

params:
    description: "Website of Leo Kim"
    author: Jungjoon Leo Kim
    # googleAnalyticsID: "G-FQDGD8LV4J"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","misc"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jungjoon Leo Kim
          subtitle: "
Hello! I am a Postdoctoral Fellow at York University in Toronto, Ontario, Canada. I am a theoretical physicist, interested in physics beyond the Standard Model of Particle Physics and dark matter phenomenology, primarily in the context of cosmology and astrophysics. Prior to working at York, I received my PhD in Physics working with [Joe Bramante](https://www.queensu.ca/academia/bramante/) at Queen's University in Kingston, Ontario, Canada, and my Master of Mathematics working with [Ghazal Geshnizjani](https://ghazalgeshnizjani.wordpress.com/) at the University of Waterloo in Waterloo, Ontario, Canada.


<br>


An updated list of my publications can be found on my [inspire page](https://inspirehep.net/authors/1945407) and my CV can be found [here](cv.pdf).
"
          imageUrl: "icon.png"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Research
              url: research/
            - name: Publications
              url: https://inspirehep.net/authors/1945407
            - name: Misc
              url: misc/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jlkim@yorku.ca
        - name: Google Scholar
          url: https://scholar.google.ca/citations?user=laP7g0oAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/jlkim
        - name: Bluesky
          url: https://bsky.app/profile/jjlkim.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "J. Leo Kim"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2


